--- aws.nvim – DynamoDB scan/query: shared state type and filter parser
local M = {}

-------------------------------------------------------------------------------
-- State type
-------------------------------------------------------------------------------

---@class DdbFilter
---@field attr      string   attribute name
---@field condition string   "="  "<>"  "<"  "<="  ">"  ">="  "begins_with"  "contains"
---@field type      string   "S"|"N"|"B"
---@field value     string

---@class DdbKeySchema
---@field name string   attribute name
---@field type string   "S"|"N"|"B"

---@class DynamoDbScanState
---@field table_name    string
---@field mode          "scan"|"query"
---@field schema_pk     DdbKeySchema|nil  real partition key from describe-table
---@field schema_sk     DdbKeySchema|nil  real sort key from describe-table (nil if none)
---@field schema_loaded boolean           true once describe-table has returned
---@field pk_name       string|nil
---@field pk_value      string|nil
---@field pk_type       string          "S"|"N"|"B"
---@field sk_name       string|nil
---@field sk_op         string|nil      "="|"<"|"<="|">"|">="|"begins_with"|"between"
---@field sk_value      string|nil
---@field sk_value2     string|nil      second value for between
---@field sk_type       string
---@field index_name    string|nil
---@field filters       DdbFilter[]     ordered list of filter rows
---@field items         table[]
---@field last_key      string|nil
---@field page          integer
---@field fetching      boolean
---@field json_view     boolean
---@field region        string
---@field profile       string|nil

--- Condition labels shown in the form (index = canonical operator).
M.CONDITIONS = {
  "Equal to",
  "Not equal to",
  "Less than",
  "Less than or equal to",
  "Greater than",
  "Greater than or equal to",
  "begins_with",
  "contains",
}

--- Map from display label to DynamoDB operator used in expressions.
M.CONDITION_OP = {
  ["Equal to"] = "=",
  ["Not equal to"] = "<>",
  ["Less than"] = "<",
  ["Less than or equal to"] = "<=",
  ["Greater than"] = ">",
  ["Greater than or equal to"] = ">=",
  ["begins_with"] = "begins_with",
  ["contains"] = "contains",
}

M.TYPES = { "String", "Number", "Binary" }
M.TYPE_CODE = { ["String"] = "S", ["Number"] = "N", ["Binary"] = "B" }
M.TYPE_LABEL = { S = "String", N = "Number", B = "Binary" }

M.SK_OPS = {
  "=",
  "<",
  "<=",
  ">",
  ">=",
  "begins_with",
  "between",
}

-------------------------------------------------------------------------------
-- DynamoDB reserved words (auto-alias with # in expressions)
-------------------------------------------------------------------------------

M.RESERVED = {
  ABORT = 1,
  ABSOLUTE = 1,
  ACTION = 1,
  ADD = 1,
  AFTER = 1,
  AGENT = 1,
  ALL = 1,
  ALLOCATE = 1,
  ALTER = 1,
  ANALYZE = 1,
  AND = 1,
  ANY = 1,
  ARCHIVE = 1,
  ARE = 1,
  ARRAY = 1,
  AS = 1,
  ASC = 1,
  ASCII = 1,
  ASENSITIVE = 1,
  ASSERTION = 1,
  ASYMMETRIC = 1,
  AT = 1,
  ATOMIC = 1,
  ATTACH = 1,
  ATTRIBUTE = 1,
  AUTH = 1,
  AUTHORIZATION = 1,
  AUTHORIZE = 1,
  AUTO = 1,
  AVG = 1,
  BACK = 1,
  BACKUP = 1,
  BASE = 1,
  BATCH = 1,
  BEFORE = 1,
  BEGIN = 1,
  BETWEEN = 1,
  BIGINT = 1,
  BINARY = 1,
  BIT = 1,
  BLOB = 1,
  BLOCK = 1,
  BOOLEAN = 1,
  BOTH = 1,
  BREADTH = 1,
  BUCKET = 1,
  BULK = 1,
  BY = 1,
  CALL = 1,
  CALLED = 1,
  CALLING = 1,
  CASCADE = 1,
  CASCADED = 1,
  CASE = 1,
  CAST = 1,
  CATALOG = 1,
  CHAR = 1,
  CHARACTER = 1,
  CHECK = 1,
  CLASS = 1,
  CLOB = 1,
  CLOSE = 1,
  CLUSTER = 1,
  CLUSTERED = 1,
  CLUSTERING = 1,
  CLUSTERS = 1,
  COALESCE = 1,
  COLLATE = 1,
  COLUMN = 1,
  COLUMNS = 1,
  COMBINE = 1,
  COMMENT = 1,
  COMMIT = 1,
  COMPACT = 1,
  COMPILE = 1,
  COMPRESS = 1,
  CONDITION = 1,
  CONFLICT = 1,
  CONNECT = 1,
  CONNECTION = 1,
  CONSISTENCY = 1,
  CONSISTENT = 1,
  CONSTRAINT = 1,
  CONSTRAINTS = 1,
  CONTINUE = 1,
  CONVERT = 1,
  COPY = 1,
  CORRESPONDING = 1,
  COUNT = 1,
  COUNTER = 1,
  CREATE = 1,
  CROSS = 1,
  CUBE = 1,
  CURRENT = 1,
  CURSOR = 1,
  CYCLE = 1,
  DATA = 1,
  DATABASE = 1,
  DATE = 1,
  DATETIME = 1,
  DAY = 1,
  DEALLOCATE = 1,
  DEC = 1,
  DECIMAL = 1,
  DECLARE = 1,
  DEFAULT = 1,
  DEFERRABLE = 1,
  DEFERRED = 1,
  DELETE = 1,
  DEPTH = 1,
  DEREF = 1,
  DESC = 1,
  DESCRIBE = 1,
  DESCRIPTOR = 1,
  DETACH = 1,
  DETERMINISTIC = 1,
  DIAGNOSTICS = 1,
  DIRECTORIES = 1,
  DISABLE = 1,
  DISCONNECT = 1,
  DISTINCT = 1,
  DISTRIBUTE = 1,
  DO = 1,
  DOUBLE = 1,
  DROP = 1,
  DUMP = 1,
  DURATION = 1,
  DYNAMIC = 1,
  EACH = 1,
  ELEMENT = 1,
  ELSE = 1,
  ELSEIF = 1,
  EMPTY = 1,
  ENABLE = 1,
  END = 1,
  EQUAL = 1,
  ERROR = 1,
  ESCAPE = 1,
  EVAL = 1,
  EVALUATE = 1,
  EXCEEDED = 1,
  EXCEPT = 1,
  EXCLUSIVE = 1,
  EXEC = 1,
  EXECUTE = 1,
  EXISTS = 1,
  EXPLAIN = 1,
  EXPLODE = 1,
  EXPORT = 1,
  EXPRESSION = 1,
  EXTENDED = 1,
  EXTERNAL = 1,
  FAIL = 1,
  FINAL = 1,
  FINISH = 1,
  FIRST = 1,
  FIXED = 1,
  FLATTERN = 1,
  FLOAT = 1,
  FOR = 1,
  FORCE = 1,
  FOREIGN = 1,
  FORMAT = 1,
  FORWARD = 1,
  FOUND = 1,
  FREE = 1,
  FROM = 1,
  FULL = 1,
  FUNCTION = 1,
  FUNCTIONS = 1,
  GENERAL = 1,
  GENERATE = 1,
  GET = 1,
  GLOB = 1,
  GLOBAL = 1,
  GO = 1,
  GOTO = 1,
  GRANT = 1,
  GREATER = 1,
  GROUP = 1,
  GROUPING = 1,
  HANDLER = 1,
  HASH = 1,
  HAVE = 1,
  HAVING = 1,
  HEAP = 1,
  HIDDEN = 1,
  HOLD = 1,
  HOUR = 1,
  IDENTIFIED = 1,
  IDENTITY = 1,
  IF = 1,
  IGNORE = 1,
  IMMEDIATE = 1,
  IMPORT = 1,
  IN = 1,
  INCLUDING = 1,
  INCLUSIVE = 1,
  INCREMENT = 1,
  INCREMENTAL = 1,
  INDEX = 1,
  INDEXED = 1,
  INDEXES = 1,
  INDICATOR = 1,
  INFINITE = 1,
  INITIALLY = 1,
  INLINE = 1,
  INNER = 1,
  INNTER = 1,
  INOUT = 1,
  INPUT = 1,
  INSENSITIVE = 1,
  INSERT = 1,
  INSTEAD = 1,
  INT = 1,
  INTEGER = 1,
  INTERSECT = 1,
  INTERVAL = 1,
  INTO = 1,
  INVALIDATE = 1,
  IS = 1,
  ISOLATION = 1,
  ITEM = 1,
  ITEMS = 1,
  ITERATE = 1,
  JOIN = 1,
  KEY = 1,
  KEYS = 1,
  LAG = 1,
  LANGUAGE = 1,
  LARGE = 1,
  LAST = 1,
  LATERAL = 1,
  LEAD = 1,
  LEADING = 1,
  LEAVE = 1,
  LEFT = 1,
  LENGTH = 1,
  LESS = 1,
  LEVEL = 1,
  LIKE = 1,
  LIMIT = 1,
  LIMITED = 1,
  LINES = 1,
  LIST = 1,
  LOAD = 1,
  LOCAL = 1,
  LOCALTIME = 1,
  LOCALTIMESTAMP = 1,
  LOCATION = 1,
  LOCATOR = 1,
  LOCK = 1,
  LOCKS = 1,
  LOG = 1,
  LOGED = 1,
  LONG = 1,
  LOOP = 1,
  LOWER = 1,
  MAP = 1,
  MATCH = 1,
  MATERIALIZED = 1,
  MAX = 1,
  MAXLEN = 1,
  MEMBER = 1,
  MERGE = 1,
  METHOD = 1,
  METRICS = 1,
  MIN = 1,
  MINUS = 1,
  MINUTE = 1,
  MISSING = 1,
  MOD = 1,
  MODE = 1,
  MODIFIES = 1,
  MODIFY = 1,
  MODULE = 1,
  MONTH = 1,
  MULTI = 1,
  MULTISET = 1,
  NAME = 1,
  NAMES = 1,
  NATIONAL = 1,
  NATURAL = 1,
  NCHAR = 1,
  NCLOB = 1,
  NEW = 1,
  NEXT = 1,
  NO = 1,
  NONE = 1,
  NOT = 1,
  NULL = 1,
  NULLIF = 1,
  NUMBER = 1,
  NUMERIC = 1,
  OBJECT = 1,
  OF = 1,
  OFFLINE = 1,
  OFFSET = 1,
  OLD = 1,
  ON = 1,
  ONLINE = 1,
  ONLY = 1,
  OPAQUE = 1,
  OPEN = 1,
  OPERATOR = 1,
  OPTION = 1,
  OR = 1,
  ORDER = 1,
  ORDINALITY = 1,
  OTHER = 1,
  OTHERS = 1,
  OUT = 1,
  OUTER = 1,
  OUTPUT = 1,
  OVER = 1,
  OVERLAPS = 1,
  OVERRIDE = 1,
  OWNER = 1,
  PAD = 1,
  PARALLEL = 1,
  PARAMETER = 1,
  PARAMETERS = 1,
  PARTIAL = 1,
  PARTITION = 1,
  PARTITIONED = 1,
  PARTITIONS = 1,
  PATH = 1,
  PERCENT = 1,
  PERCENTILE = 1,
  PERMISSION = 1,
  PERMISSIONS = 1,
  PIPE = 1,
  PIPELINED = 1,
  PLAN = 1,
  POOL = 1,
  POSITION = 1,
  PRECISION = 1,
  PREPARE = 1,
  PRESERVE = 1,
  PRIMARY = 1,
  PRIOR = 1,
  PRIVATE = 1,
  PRIVILEGES = 1,
  PROCEDURE = 1,
  PROCESSED = 1,
  PROJECT = 1,
  PROJECTION = 1,
  PROPERTY = 1,
  PROVISIONING = 1,
  PUBLIC = 1,
  PUT = 1,
  QUERY = 1,
  QUIT = 1,
  QUORUM = 1,
  RAISE = 1,
  RANDOM = 1,
  RANGE = 1,
  RANK = 1,
  RAW = 1,
  READ = 1,
  READS = 1,
  REAL = 1,
  REBUILD = 1,
  RECORD = 1,
  RECURSIVE = 1,
  REDUCE = 1,
  REF = 1,
  REFERENCE = 1,
  REFERENCES = 1,
  REFERENCING = 1,
  REGEXP = 1,
  REGION = 1,
  REINDEX = 1,
  RELATIVE = 1,
  RELEASE = 1,
  REMAINDER = 1,
  RENAME = 1,
  REPEAT = 1,
  REPLACE = 1,
  REQUEST = 1,
  RESET = 1,
  RESIGNAL = 1,
  RESOURCE = 1,
  RESPONSE = 1,
  RESTORE = 1,
  RESTRICT = 1,
  RESULT = 1,
  RETURN = 1,
  RETURNING = 1,
  RETURNS = 1,
  REVERSE = 1,
  RIGHT = 1,
  ROLE = 1,
  ROLES = 1,
  ROLLBACK = 1,
  ROLLUP = 1,
  ROUTINE = 1,
  ROW = 1,
  ROWS = 1,
  RULE = 1,
  SAVEPOINT = 1,
  SCROLL = 1,
  SEARCH = 1,
  SECOND = 1,
  SECTION = 1,
  SEGMENT = 1,
  SELECT = 1,
  SELF = 1,
  SENSITIVE = 1,
  SEQUENCE = 1,
  SERIALIZABLE = 1,
  SESSION = 1,
  SET = 1,
  SETS = 1,
  SIGNAL = 1,
  SIMILAR = 1,
  SIZE = 1,
  SKEWED = 1,
  SMALLINT = 1,
  SNAPSHOT = 1,
  SOME = 1,
  SPACE = 1,
  SPECIFIC = 1,
  SPECIFICTYPE = 1,
  SPLIT = 1,
  SQL = 1,
  SQLCODE = 1,
  SQLERROR = 1,
  SQLEXCEPTION = 1,
  SQLSTATE = 1,
  SQLWARNING = 1,
  START = 1,
  STATE = 1,
  STATIC = 1,
  STATUS = 1,
  STORAGE = 1,
  STORE = 1,
  STORED = 1,
  STREAM = 1,
  STRING = 1,
  STRUCT = 1,
  STYLE = 1,
  SUB = 1,
  SUBMULTISET = 1,
  SUBPARTITION = 1,
  SUBSTRING = 1,
  SUBTYPE = 1,
  SUM = 1,
  SUPER = 1,
  SYMMETRIC = 1,
  SYNONYM = 1,
  SYSTEM = 1,
  TABLE = 1,
  TABLESAMPLE = 1,
  TEMP = 1,
  TEMPORARY = 1,
  TERMINATED = 1,
  TEXT = 1,
  THAN = 1,
  THEN = 1,
  TIME = 1,
  TIMESTAMP = 1,
  TIMEZONE = 1,
  TINYINT = 1,
  TO = 1,
  TOKEN = 1,
  TOTAL = 1,
  TOUCH = 1,
  TRAILING = 1,
  TRANSACTION = 1,
  TRANSFORM = 1,
  TRANSLATE = 1,
  TRANSLATION = 1,
  TREAT = 1,
  TRIGGER = 1,
  TRIM = 1,
  TRUE = 1,
  TRUNCATE = 1,
  TTL = 1,
  TUPLE = 1,
  TYPE = 1,
  TYPES = 1,
  UNDER = 1,
  UNION = 1,
  UNIQUE = 1,
  UNIT = 1,
  UNKNOWN = 1,
  UNLOGGED = 1,
  UNNEST = 1,
  UNPROCESSED = 1,
  UNSIGNED = 1,
  UNTIL = 1,
  UPDATE = 1,
  UPPER = 1,
  URL = 1,
  USAGE = 1,
  USE = 1,
  USER = 1,
  USERS = 1,
  USING = 1,
  UUID = 1,
  VACUUM = 1,
  VALUE = 1,
  VALUED = 1,
  VALUES = 1,
  VARCHAR = 1,
  VARIABLE = 1,
  VARIANCE = 1,
  VARINT = 1,
  VARYING = 1,
  VIEW = 1,
  VIEWS = 1,
  VIRTUAL = 1,
  VOID = 1,
  WAIT = 1,
  WHEN = 1,
  WHENEVER = 1,
  WHERE = 1,
  WHILE = 1,
  WINDOW = 1,
  WITH = 1,
  WITHIN = 1,
  WITHOUT = 1,
  WORK = 1,
  WRAPPED = 1,
  WRITE = 1,
  YEAR = 1,
  ZONE = 1,
}

-------------------------------------------------------------------------------
-- Filter expression builder from structured filter rows
-------------------------------------------------------------------------------

--- Build FilterExpression, EAN, and EAV from the list of DdbFilter rows.
---@param filters DdbFilter[]
---@return string|nil  filter_expr
---@return table       ean   { ["#alias"] = "attrName" }
---@return table       eav   { [":placeholder"] = { S|N|B = "val" } }
function M.build_filter_expression(filters)
  if not filters or #filters == 0 then
    return nil, {}, {}
  end

  local ean = {}
  local eav = {}
  local parts = {}
  local counters = {}

  local function alias_name(attr)
    local up = attr:upper()
    if M.RESERVED[up] then
      local a = "#" .. attr:lower():gsub("[^%w_]", "_")
      ean[a] = attr
      return a
    end
    return attr
  end

  local function alias_value(attr, val, type_code)
    local base = attr:lower():gsub("[^%w_]", "_")
    counters[base] = (counters[base] or -1) + 1
    local ph = ":" .. base .. (counters[base] > 0 and tostring(counters[base]) or "")
    eav[ph] = { [type_code] = val }
    return ph
  end

  for _, f in ipairs(filters) do
    if f.attr ~= "" and f.value ~= "" then
      local op = M.CONDITION_OP[f.condition] or "="
      local type_code = M.TYPE_CODE[f.type] or "S"
      local an = alias_name(f.attr)
      local vn = alias_value(f.attr, f.value, type_code)

      if op == "begins_with" or op == "contains" then
        table.insert(parts, op .. "(" .. an .. ", " .. vn .. ")")
      else
        table.insert(parts, an .. " " .. op .. " " .. vn)
      end
    end
  end

  if #parts == 0 then
    return nil, {}, {}
  end
  return table.concat(parts, " AND "), ean, eav
end

-------------------------------------------------------------------------------
-- Default state factory
-------------------------------------------------------------------------------

---@param table_name string
---@param region     string
---@param profile    string|nil
---@return DynamoDbScanState
function M.new_state(table_name, region, profile)
  return {
    table_name = table_name,
    mode = "scan",
    schema_pk = nil,
    schema_sk = nil,
    schema_loaded = false,
    pk_name = nil,
    pk_value = nil,
    pk_type = "S",
    sk_name = nil,
    sk_op = nil,
    sk_value = nil,
    sk_value2 = nil,
    sk_type = "S",
    index_name = nil,
    filters = {},
    items = {},
    last_key = nil,
    page = 1,
    fetching = false,
    json_view = false,
    region = region,
    profile = profile,
  }
end

return M
